### ISSUE TITLE
When endpoint creation fails, resources are not cleaned up properly

### ISSUE THREAD

**Issue by poussa** [IntelAI/inference-model-manager#85] opened 2019-03-27 12:14 UTC
When you try to create an endpoint and it fails (e.g. due to invalid JSON in $ENDPOINT_RESOURCES), the resources are not properly cleaned up. The next endpoint creation fails with 

`{"title": "An error occurred during endpoint creation: Conflict"}`

Logs from mgt:

```
INFO:management_api.authenticate.authenticate:Request path: /tenants/default-tenant/endpoints, method POST
ERROR:management_api.utils.errors_handling:Unexpected error occurred: ('Invalid JSON', 'Could not parse JSON body - Extra data: line 1 column 169 (char 168)')
Request: <Request: POST 'https://mgt.imm.net/tenants/default-tenant/endpoints'>  Params: {'tenant_name': 'default-tenant'}
ERROR:management_api.utils.errors_handling:Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/falcon/media/json.py", line 15, in deserialize
    return json.loads(raw.decode('utf-8'))
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 169 (char 168)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/falcon/api.py", line 244, in __call__
    responder(req, resp, **params)
  File "/usr/lib/python3.7/site-packages/falcon/media/validators/jsonschema.py", line 45, in wrapper
    jsonschema.validate(req.media, schema, format_checker=jsonschema.FormatChecker())
  File "/usr/lib/python3.7/site-packages/falcon/request.py", line 965, in media
    self._media = handler.deserialize(raw)
  File "/usr/lib/python3.7/site-packages/falcon/media/json.py", line 19, in deserialize
    'Could not parse JSON body - {0}'.format(err)
falcon.errors.HTTPBadRequest: ('Invalid JSON', 'Could not parse JSON body - Extra data: line 1 column 169 (char 168)')

INFO:management_api.authenticate.authenticate:Checking token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImI2YTU0ZWQzMzdjYjY5N2M4YWFmMmZiMjFhMDYzYTExMjZlMWYwNDkifQ.eyJpc3MiOiJodHRwczovL2RleC5pbW0ubmV0OjQ0My9kZXgiLCJzdWIiOiJDaU5qYmoxMWMyVnlMRzkxUFZCbGIzQnNaU3hrWXoxbGVHRnRjR3hsTEdSalBXOXlaeElFYkdSaGNBIiwiYXVkIjoiZXhhbXBsZS1hcHAiLCJleHAiOjE1NTM2ODg3NDcsImlhdCI6MTU1MzY4NTE0NywiYXRfaGFzaCI6IkpLdlhkdGkyZGtoV0ltV0hWcXRJQ3ciLCJlbWFpbCI6InVzZXJAZXhhbXBsZS5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZ3JvdXBzIjpbImFkbWluIl19.wQ69oWwUFdrdrUnLH2z8yCDSQ62OisreWqmdqLEToFm70hSMQl8NPO-Krmn549f7BJOata8Q60VupKuYmYgZOfRAiXVUSSpokp8cfcr5RBUrpiw-rwdrk8aBKH5P_l_gq1JA74AnUb_fvzWUvICaEUFL1nK9kooC8U1Q01hrAGo-K1-wpRtSfZnvqzU0EnDV8xZr7wdmINmY0dpIv3tGWkxS3M2J5WxnM-_d8qw3-Spl_QHXKwHbuqWHLNxpt6nlAcXW9Sv690JwY0_aWpAvRpbH6hgJpj5Hx3rJ_L9tlzUSAVhj5yrS6SyqSy8ITx2lXUkXncW_6_oTnbaGiRiuOQ
INFO:management_api.authenticate.authenticate:Trying key number : 0
INFO:management_api.authenticate.authenticate:Decoded
INFO:management_api.authenticate.authenticate:Using service account token
INFO:management_api.authenticate.authenticate:Decoded token : {'iss': 'https://dex.imm.net:443/dex', 'sub': 'CiNjbj11c2VyLG91PVBlb3BsZSxkYz1leGFtcGxlLGRjPW9yZxIEbGRhcA', 'aud': 'example-app', 'exp': 1553688747, 'iat': 1553685147, 'at_hash': 'JKvXdti2dkhWImWHVqtICw', 'email': 'user@example.com', 'email_verified': True, 'groups': ['admin']}
INFO:management_api.authenticate.authenticate:Request path: /tenants/default-tenant/endpoints, method POST
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Resetting dropped connection: minio.imm.net
INFO:management_api.tenants.tenants_utils:Tenant already exists: True
ERROR:management_api.utils.errors_handling:An error occurred during endpoint creation: (409)
Reason: Conflict
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Wed, 27 Mar 2019 12:03:19 GMT', 'Content-Length': '264'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"inference-endpoints.ai.intel.com \"endpoint-1\" already exists","reason":"AlreadyExists","details":{"name":"endpoint-1","group":"ai.intel.com","kind":"inference-endpoints"},"code":409}
```

**Comment by pawel-pieniazek** [comment] 2019-03-28 12:49
We try to reproduce this problem, but it works for us. 
@poussa are you sure that `endpoint-1` was not created earlier on this platform? 
We also checked in code, that if JSON is wrong, no resources are created. So there is nothing to be cleaned.

**Comment by pawel-pieniazek** [comment] 2019-04-04 11:21
Closing, because we could not reproduce it. Feel free to reopen if it occurs again

**Closed by pawel-pieniazek** 2019-04-04 11:21 UTC
Labels: P1
